"""
Type definitions for Google Interactions API

Auto-generated from OpenAPI spec: https://ai.google.dev/static/api/interactions.openapi.json
See README.md for regeneration instructions.
"""

from litellm.types.interactions.generated import (
    AgentOption,
    Annotation,
    AudioContent,
    CancelInteractionResult,
    CodeExecution,
    CodeExecutionCallStep,
    CodeExecutionResultStep,
    ComputerUse,
    Content,
    ContentDelta,
    ContentStart,
    ContentStop,
    CreateAgentInteractionParams,
    CreateModelInteractionParams,
    DeepResearchAgentConfig,
    DeleteInteractionResult,
    DocumentContent,
    DynamicAgentConfig,
    ErrorEvent,
    FileSearch,
    FileSearchResultStep,
    Function,
    FunctionCallStep,
    FunctionResultStep,
    GenerationConfig,
    GoogleSearch,
    GoogleSearchCallStep,
    GoogleSearchResultStep,
    ImageContent,
    Interaction,
    InteractionCreatedEvent,
    InteractionCompletedEvent,
    InteractionInput,
    InteractionsAPIOptionalRequestParams,
    InteractionsAPIResponse,
    InteractionsAPIStreamingResponse,
    InteractionSseEvent,
    InteractionTool,
    InteractionToolChoiceConfig,
    McpServer,
    McpServerToolCallStep,
    McpServerToolResultStep,
    ModelOption,
    ResponseModality,
)
from litellm.types.interactions.generated import (
    Status2 as InteractionStatus,  # Main request/response types; Content types; Turn for multi-turn conversations; Tool types; Config types; Usage; Status enum; Events for streaming; Agent configs; Model/Agent options; Response modality; Annotation; LiteLLM types; Backwards compat aliases
)
from litellm.types.interactions.generated import (
    TextContent,
    ThoughtContent,
    Tool,
    ToolChoiceConfig,
    Turn,
    UrlContext,
    UrlContextCallStep,
    UrlContextResultStep,
    Usage,
    VideoContent,
)

__all__ = [
    # Generated types
    "CreateModelInteractionParams",
    "CreateAgentInteractionParams",
    "Interaction",
    "Content",
    "TextContent",
    "ImageContent",
    "AudioContent",
    "DocumentContent",
    "VideoContent",
    "ThoughtContent",
    "FunctionCallStep",
    "FunctionResultStep",
    "CodeExecutionCallStep",
    "CodeExecutionResultStep",
    "UrlContextCallStep",
    "UrlContextResultStep",
    "GoogleSearchCallStep",
    "GoogleSearchResultStep",
    "McpServerToolCallStep",
    "McpServerToolResultStep",
    "FileSearchResultStep",
    "Turn",
    "Tool",
    "Function",
    "GoogleSearch",
    "CodeExecution",
    "UrlContext",
    "ComputerUse",
    "McpServer",
    "FileSearch",
    "GenerationConfig",
    "ToolChoiceConfig",
    "Usage",
    "InteractionStatus",
    "InteractionCreatedEvent",
    "InteractionCompletedEvent",
    "InteractionSseEvent",
    "ContentStart",
    "ContentDelta",
    "ContentStop",
    "ErrorEvent",
    "DynamicAgentConfig",
    "DeepResearchAgentConfig",
    "ModelOption",
    "AgentOption",
    "ResponseModality",
    "Annotation",
    # LiteLLM types
    "InteractionInput",
    "InteractionsAPIResponse",
    "InteractionsAPIStreamingResponse",
    "DeleteInteractionResult",
    "CancelInteractionResult",
    "InteractionsAPIOptionalRequestParams",
    # Backwards compat
    "InteractionTool",
    "InteractionToolChoiceConfig",
]
