# generated by datamodel-codegen:
#   filename:  https://ai.google.dev/static/api/interactions.openapi.json
#   timestamp: 2026-05-08T03:29:47+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, Base64Str, BaseModel, Field, RootModel


class UrlCitation(BaseModel):
    type: Literal['url_citation']
    url: str | None = Field(None, description='The URL.')
    title: str | None = Field(None, description='The title of the URL.')
    start_index: int | None = Field(
        None,
        description='Start of segment of the response that is attributed to this source.\n\nIndex indicates the start of the segment, measured in bytes.',
    )
    end_index: int | None = Field(
        None, description='End of the attributed segment, exclusive.'
    )


class FileCitation(BaseModel):
    type: Literal['file_citation']
    document_uri: str | None = Field(None, description='The URI of the file.')
    file_name: str | None = Field(None, description='The name of the file.')
    source: str | None = Field(
        None, description='Source attributed for a portion of the text.'
    )
    custom_metadata: dict[str, Any] | None = Field(
        None, description='User provided metadata about the retrieved context.'
    )
    page_number: int | None = Field(
        None, description='Page number of the cited document, if applicable.'
    )
    media_id: str | None = Field(
        None, description='Media ID in-case of image citations, if applicable.'
    )
    start_index: int | None = Field(
        None,
        description='Start of segment of the response that is attributed to this source.\n\nIndex indicates the start of the segment, measured in bytes.',
    )
    end_index: int | None = Field(
        None, description='End of the attributed segment, exclusive.'
    )


class ReviewSnippet(BaseModel):
    title: str | None = Field(None, description='Title of the review.')
    url: str | None = Field(
        None, description='A link that corresponds to the user review on Google Maps.'
    )
    review_id: str | None = Field(None, description='The ID of the review snippet.')


class MimeType(Enum):
    image_png = 'image/png'
    image_jpeg = 'image/jpeg'
    image_webp = 'image/webp'
    image_heic = 'image/heic'
    image_heif = 'image/heif'
    image_gif = 'image/gif'
    image_bmp = 'image/bmp'
    image_tiff = 'image/tiff'


class MimeType1(Enum):
    audio_wav = 'audio/wav'
    audio_mp3 = 'audio/mp3'
    audio_aiff = 'audio/aiff'
    audio_aac = 'audio/aac'
    audio_ogg = 'audio/ogg'
    audio_flac = 'audio/flac'
    audio_mpeg = 'audio/mpeg'
    audio_m4a = 'audio/m4a'
    audio_l16 = 'audio/l16'
    audio_opus = 'audio/opus'
    audio_alaw = 'audio/alaw'
    audio_mulaw = 'audio/mulaw'


class AudioContent(BaseModel):
    type: Literal['audio']
    data: Base64Str | None = Field(None, description='The audio content.')
    uri: str | None = Field(None, description='The URI of the audio.')
    mime_type: MimeType1 | None = Field(None, description='The mime type of the audio.')
    channels: int | None = Field(None, description='The number of audio channels.')
    sample_rate: int | None = Field(None, description='The sample rate of the audio.')


class MimeType2(Enum):
    application_pdf = 'application/pdf'


class DocumentContent(BaseModel):
    type: Literal['document']
    data: Base64Str | None = Field(None, description='The document content.')
    uri: str | None = Field(None, description='The URI of the document.')
    mime_type: MimeType2 | None = Field(
        None, description='The mime type of the document.'
    )


class MimeType3(Enum):
    video_mp4 = 'video/mp4'
    video_mpeg = 'video/mpeg'
    video_mpg = 'video/mpg'
    video_mov = 'video/mov'
    video_avi = 'video/avi'
    video_x_flv = 'video/x-flv'
    video_webm = 'video/webm'
    video_wmv = 'video/wmv'
    video_3gpp = 'video/3gpp'


class Language(Enum):
    python = 'python'


class CodeExecutionCallArguments(BaseModel):
    language: Language | None = Field(
        None, description='Programming language of the `code`.'
    )
    code: str | None = Field(None, description='The code to be executed.')


class UrlContextCallArguments(BaseModel):
    urls: list[str] | None = Field(None, description='The URLs to fetch.')


class GoogleSearchCallArguments(BaseModel):
    queries: list[str] | None = Field(
        None, description='Web search queries for the following-up web search.'
    )


class GoogleMapsCallArguments(BaseModel):
    queries: list[str] | None = Field(None, description='The queries to be executed.')


class Status(Enum):
    success = 'success'
    error = 'error'
    paywall = 'paywall'
    unsafe = 'unsafe'


class UrlContextResult(BaseModel):
    url: str | None = Field(None, description='The URL that was fetched.')
    status: Status | None = Field(None, description='The status of the URL retrieval.')


class GoogleSearchResult(BaseModel):
    search_suggestions: str | None = Field(
        None,
        description='Web content snippet that can be embedded in a web page or an app webview.',
    )


class FileSearchResult(BaseModel):
    pass


class Places(BaseModel):
    place_id: str | None = Field(
        None, description='The ID of the place, in `places/{place_id}` format.'
    )
    name: str | None = Field(None, description='Title of the place.')
    url: str | None = Field(None, description='URI reference of the place.')
    review_snippets: list[ReviewSnippet] | None = Field(
        None,
        description='Snippets of reviews that are used to generate answers about the\nfeatures of a given place in Google Maps.',
    )


class FunctionCallStep(BaseModel):
    type: Literal['function_call']
    name: str = Field(..., description='Required. The name of the tool to call.')
    arguments: dict[str, Any] = Field(
        ..., description='Required. The arguments to pass to the function.'
    )
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class CodeExecutionCallStepArguments(BaseModel):
    language: Language | None = Field(
        None, description='Programming language of the `code`.'
    )
    code: str | None = Field(None, description='The code to be executed.')


class UrlContextCallStepArguments(BaseModel):
    urls: list[str] | None = Field(None, description='The URLs to fetch.')


class McpServerToolCallStep(BaseModel):
    type: Literal['mcp_server_tool_call']
    name: str = Field(
        ..., description='Required. The name of the tool which was called.'
    )
    server_name: str = Field(
        ..., description='Required. The name of the used MCP server.'
    )
    arguments: dict[str, Any] = Field(
        ..., description='Required. The JSON object of arguments for the function.'
    )
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class SearchType(Enum):
    web_search = 'web_search'
    image_search = 'image_search'
    enterprise_web_search = 'enterprise_web_search'


class GoogleSearchCallStepArguments(BaseModel):
    queries: list[str] | None = Field(
        None, description='Web search queries for the following-up web search.'
    )


class FileSearchCallStep(BaseModel):
    type: Literal['file_search_call']
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class GoogleMapsCallStepArguments(BaseModel):
    queries: list[str] | None = Field(None, description='The queries to be executed.')


class CodeExecutionResultStep(BaseModel):
    type: Literal['code_execution_result']
    result: str = Field(..., description='Required. The output of the code execution.')
    is_error: bool | None = Field(
        None, description='Whether the code execution resulted in an error.'
    )
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class UrlContextResultItem(BaseModel):
    url: str | None = Field(None, description='The URL that was fetched.')
    status: Status | None = Field(None, description='The status of the URL retrieval.')


class GoogleSearchResultItem(BaseModel):
    search_suggestions: str | None = Field(
        None,
        description='Web content snippet that can be embedded in a web page or an app webview.',
    )


class FileSearchResultStep(BaseModel):
    type: Literal['file_search_result']
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class GoogleMapsResultPlaces(BaseModel):
    place_id: str | None = None
    name: str | None = None
    url: str | None = None
    review_snippets: list[ReviewSnippet] | None = None


class MimeType4(Enum):
    audio_mp3 = 'audio/mp3'
    audio_ogg_opus = 'audio/ogg_opus'
    audio_l16 = 'audio/l16'
    audio_wav = 'audio/wav'
    audio_alaw = 'audio/alaw'
    audio_mulaw = 'audio/mulaw'


class Delivery(Enum):
    inline = 'inline'
    url = 'url'


class AudioResponseFormat(BaseModel):
    type: Literal['audio']
    mimeType: MimeType4 | None = Field(
        None, description='The MIME type of the audio output.'
    )
    delivery: Delivery | None = Field(
        None, description='The delivery mode for the audio output.'
    )
    sampleRate: int | None = Field(None, description='Sample rate in Hz.')
    bitRate: int | None = Field(
        None,
        description='Bit rate in bits per second (bps). Only applicable for compressed formats\n(MP3, Opus).',
    )


class MimeType5(Enum):
    application_json = 'application/json'
    text_plain = 'text/plain'


class TextResponseFormat(BaseModel):
    type: Literal['text']
    mimeType: MimeType5 | None = Field(
        None, description='The MIME type of the text output.'
    )
    schema_: dict[str, Any] | None = Field(
        None,
        alias='schema',
        description='The JSON schema that the output should conform to. Only applicable when\nmime_type is application/json.',
    )


class MimeType6(Enum):
    image_jpeg = 'image/jpeg'


class AspectRatio(Enum):
    field_1_1 = '1:1'
    field_2_3 = '2:3'
    field_3_2 = '3:2'
    field_3_4 = '3:4'
    field_4_3 = '4:3'
    field_4_5 = '4:5'
    field_5_4 = '5:4'
    field_9_16 = '9:16'
    field_16_9 = '16:9'
    field_21_9 = '21:9'
    field_1_8 = '1:8'
    field_8_1 = '8:1'
    field_1_4 = '1:4'
    field_4_1 = '4:1'


class ImageSize(Enum):
    field_512 = '512'
    field_1K = '1K'
    field_2K = '2K'
    field_4K = '4K'


class ImageResponseFormat(BaseModel):
    type: Literal['image']
    mimeType: MimeType6 | None = Field(
        None, description='The MIME type of the image output.'
    )
    delivery: Delivery | None = Field(
        None, description='The delivery mode for the image output.'
    )
    aspectRatio: AspectRatio | None = Field(
        None, description='The aspect ratio for the image output.'
    )
    imageSize: ImageSize | None = Field(
        None, description='The size of the image output.'
    )


class VideoResponseFormat(BaseModel):
    type: Literal['video']


class SpeechConfig(BaseModel):
    voice: str | None = Field(None, description='The voice of the speaker.')
    language: str | None = Field(None, description='The language of the speech.')
    speaker: str | None = Field(
        None,
        description="The speaker's name, it should match the speaker name given in the prompt.",
    )


class ImageSize1(Enum):
    field_1K = '1K'
    field_2K = '2K'
    field_4K = '4K'
    field_512 = '512'


class ImageConfig(BaseModel):
    aspect_ratio: AspectRatio | None = None
    image_size: ImageSize1 | None = None


class DynamicAgentConfig(BaseModel):
    type: Literal['dynamic']


class Visualization(Enum):
    off = 'off'
    auto = 'auto'


class Function(BaseModel):
    type: Literal['function']
    name: str | None = Field(None, description='The name of the function.')
    description: str | None = Field(None, description='A description of the function.')
    parameters: Any | None = Field(
        None, description="The JSON Schema for the function's parameters."
    )


class CodeExecution(BaseModel):
    type: Literal['code_execution']


class UrlContext(BaseModel):
    type: Literal['url_context']


class Environment(Enum):
    browser = 'browser'


class ComputerUse(BaseModel):
    type: Literal['computer_use']
    environment: Environment | None = Field(
        None, description='The environment being operated.'
    )
    excludedPredefinedFunctions: list[str] | None = Field(
        None,
        description='The list of predefined functions that are excluded from the model call.',
    )


class GoogleSearch(BaseModel):
    type: Literal['google_search']
    search_types: list[SearchType] | None = Field(
        None, description='The types of search grounding to enable.'
    )


class FileSearch(BaseModel):
    type: Literal['file_search']
    file_search_store_names: list[str] | None = Field(
        None, description='The file search store names to search.'
    )
    top_k: int | None = Field(
        None, description='The number of semantic retrieval chunks to retrieve.'
    )
    metadata_filter: str | None = Field(
        None,
        description='Metadata filter to apply to the semantic retrieval documents and chunks.',
    )


class GoogleMaps(BaseModel):
    type: Literal['google_maps']
    enable_widget: bool | None = Field(
        None,
        description='Whether to return a widget context token in the tool call result of the\nresponse.',
    )
    latitude: float | None = Field(
        None, description="The latitude of the user's location."
    )
    longitude: float | None = Field(
        None, description="The longitude of the user's location."
    )


class RetrievalType(Enum):
    vertex_ai_search = 'vertex_ai_search'


class VertexAISearchConfig(BaseModel):
    engine: str | None = Field(
        None, description='Optional. Used to specify Vertex AI Search engine.'
    )
    datastores: list[str] | None = Field(
        None, description='Optional. Used to specify Vertex AI Search datastores.'
    )


class Type(Enum):
    google_search = 'google_search'
    google_maps = 'google_maps'
    retrieval = 'retrieval'


class GroundingToolCount(BaseModel):
    type: Type | None = Field(
        None, description='The grounding tool type associated with the count.'
    )
    count: int | None = Field(None, description='The number of grounding tool counts.')


class WebhookConfig(BaseModel):
    uris: list[str] | None = Field(
        None,
        description='Optional. If set, these webhook URIs will be used for webhook events instead of the\nregistered webhooks.',
    )
    user_metadata: dict[str, Any] | None = Field(
        None,
        description='Optional. The user metadata that will be returned on each event emission to the\nwebhooks.',
    )


class Status2(Enum):
    in_progress = 'in_progress'
    requires_action = 'requires_action'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'
    incomplete = 'incomplete'


class InteractionStatusUpdate(BaseModel):
    event_type: Literal['interaction.status_update']
    interaction_id: str
    status: Status2
    event_id: str | None = Field(
        None,
        description='The event_id token to be used to resume the interaction stream, from\nthis event.',
    )


class TextDelta(BaseModel):
    type: Literal['text']
    text: str


class MimeType7(Enum):
    image_png = 'image/png'
    image_jpeg = 'image/jpeg'
    image_webp = 'image/webp'
    image_heic = 'image/heic'
    image_heif = 'image/heif'
    image_gif = 'image/gif'
    image_bmp = 'image/bmp'
    image_tiff = 'image/tiff'


class MimeType8(Enum):
    audio_wav = 'audio/wav'
    audio_mp3 = 'audio/mp3'
    audio_aiff = 'audio/aiff'
    audio_aac = 'audio/aac'
    audio_ogg = 'audio/ogg'
    audio_flac = 'audio/flac'
    audio_mpeg = 'audio/mpeg'
    audio_m4a = 'audio/m4a'
    audio_l16 = 'audio/l16'
    audio_opus = 'audio/opus'
    audio_alaw = 'audio/alaw'
    audio_mulaw = 'audio/mulaw'


class AudioDelta(BaseModel):
    type: Literal['audio']
    data: Base64Str | None = None
    uri: str | None = None
    mime_type: MimeType8 | None = None
    rate: int | None = Field(
        None,
        deprecated=True,
        description='Deprecated. Use sample_rate instead. The value is ignored.',
    )
    sample_rate: int | None = Field(None, description='The sample rate of the audio.')
    channels: int | None = Field(None, description='The number of audio channels.')


class MimeType9(Enum):
    application_pdf = 'application/pdf'


class DocumentDelta(BaseModel):
    type: Literal['document']
    data: Base64Str | None = None
    uri: str | None = None
    mime_type: MimeType9 | None = None


class MimeType10(Enum):
    video_mp4 = 'video/mp4'
    video_mpeg = 'video/mpeg'
    video_mpg = 'video/mpg'
    video_mov = 'video/mov'
    video_avi = 'video/avi'
    video_x_flv = 'video/x-flv'
    video_webm = 'video/webm'
    video_wmv = 'video/wmv'
    video_3gpp = 'video/3gpp'


class ThoughtSignatureDelta(BaseModel):
    type: Literal['thought_signature']
    signature: Base64Str | None = Field(
        None,
        description='Signature to match the backend source to be part of the generation.',
    )


class FunctionCallDelta(BaseModel):
    type: Literal['function_call']
    name: str
    arguments: dict[str, Any]
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class CodeExecutionCallDelta(BaseModel):
    type: Literal['code_execution_call']
    arguments: CodeExecutionCallArguments
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class UrlContextCallDelta(BaseModel):
    type: Literal['url_context_call']
    arguments: UrlContextCallArguments
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class GoogleSearchCallDelta(BaseModel):
    type: Literal['google_search_call']
    arguments: GoogleSearchCallArguments
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class McpServerToolCallDelta(BaseModel):
    type: Literal['mcp_server_tool_call']
    name: str
    server_name: str
    arguments: dict[str, Any]
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class FileSearchCallDelta(BaseModel):
    type: Literal['file_search_call']
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class GoogleMapsCallDelta(BaseModel):
    type: Literal['google_maps_call']
    arguments: GoogleMapsCallArguments | None = Field(
        None, description='The arguments to pass to the Google Maps tool.'
    )
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class CodeExecutionResultDelta(BaseModel):
    type: Literal['code_execution_result']
    result: str
    is_error: bool | None = None
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class UrlContextResultDelta(BaseModel):
    type: Literal['url_context_result']
    result: list[UrlContextResult]
    is_error: bool | None = None
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class GoogleSearchResultDelta(BaseModel):
    type: Literal['google_search_result']
    result: list[GoogleSearchResult]
    is_error: bool | None = None
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class FileSearchResultDelta(BaseModel):
    type: Literal['file_search_result']
    result: list[FileSearchResult]
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class ContentStop(BaseModel):
    event_type: Literal['content.stop']
    index: int
    event_id: str | None = Field(
        None,
        description='The event_id token to be used to resume the interaction stream, from\nthis event.',
    )


class Error(BaseModel):
    code: str | None = Field(None, description='A URI that identifies the error type.')
    message: str | None = Field(None, description='A human-readable error message.')


class ArgumentsDelta(BaseModel):
    type: Literal['arguments_delta']
    partial_arguments: str | None = None


class StepStop(BaseModel):
    event_type: Literal['step.stop']
    index: int
    event_id: str | None = Field(
        None,
        description='The event_id token to be used to resume the interaction stream, from\nthis event.',
    )


class State(Enum):
    enabled = 'enabled'
    disabled = 'disabled'
    disabled_due_to_failed_deliveries = 'disabled_due_to_failed_deliveries'


class SigningSecret(BaseModel):
    truncated_secret: str | None = Field(
        None, description='Output only. The truncated version of the signing secret.'
    )
    expire_time: AwareDatetime | None = Field(
        None, description='Output only. The expiration date of the signing secret.'
    )


class WebhookUpdate(BaseModel):
    name: str | None = Field(
        None, description='Optional. The user-provided name of the webhook.'
    )
    uri: str | None = Field(
        None, description='Optional. The URI to which webhook events will be sent.'
    )
    subscribed_events: (
        list[
            str
            | Literal['batch.succeeded']
            | Literal['batch.expired']
            | Literal['batch.failed']
            | Literal['interaction.requires_action']
            | Literal['interaction.completed']
            | Literal['interaction.failed']
            | Literal['video.generated']
        ]
        | None
    ) = Field(
        None,
        description='Optional. The events that the webhook is subscribed to.\nAvailable events:\n- batch.succeeded\n- batch.expired\n- batch.failed\n- interaction.requires_action\n- interaction.completed\n- interaction.failed\n- video.generated',
    )
    state: State | None = Field(None, description='Optional. The state of the webhook.')


class Empty(BaseModel):
    pass


class RevocationBehavior(Enum):
    revoke_previous_secrets_after_h24 = 'revoke_previous_secrets_after_h24'
    revoke_previous_secrets_immediately = 'revoke_previous_secrets_immediately'


class RotateSigningSecretRequest(BaseModel):
    revocation_behavior: RevocationBehavior | None = Field(
        None,
        description='Optional. The revocation behavior for previous signing secrets.',
    )


class RotateSigningSecretResponse(BaseModel):
    secret: str | None = Field(
        None, description='Output only. The newly generated signing secret.'
    )


class PingWebhookRequest(BaseModel):
    pass


class PingWebhookResponse(BaseModel):
    pass


class MediaResolution(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    ultra_high = 'ultra_high'


class ToolChoiceType(Enum):
    auto = 'auto'
    any = 'any'
    none = 'none'
    validated = 'validated'


class ThinkingLevel(Enum):
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'


class ThinkingSummaries(Enum):
    auto = 'auto'
    none = 'none'


class ResponseModality(Enum):
    text = 'text'
    image = 'image'
    audio = 'audio'
    video = 'video'
    document = 'document'


class ServiceTier(Enum):
    flex = 'flex'
    standard = 'standard'
    priority = 'priority'


class ModelOption(
    RootModel[
        str
        | Literal['gemini-2.5-computer-use-preview-10-2025']
        | Literal['gemini-2.5-flash']
        | Literal['gemini-2.5-flash-image']
        | Literal['gemini-2.5-flash-lite']
        | Literal['gemini-2.5-flash-lite-preview-09-2025']
        | Literal['gemini-2.5-flash-native-audio-preview-12-2025']
        | Literal['gemini-2.5-flash-preview-09-2025']
        | Literal['gemini-2.5-flash-preview-tts']
        | Literal['gemini-2.5-pro']
        | Literal['gemini-2.5-pro-preview-tts']
        | Literal['gemini-3-flash-preview']
        | Literal['gemini-3-pro-image-preview']
        | Literal['gemini-3-pro-preview']
        | Literal['gemini-3.1-pro-preview']
        | Literal['gemini-3.1-flash-image-preview']
        | Literal['gemini-3.1-flash-lite-preview']
        | Literal['gemini-3.1-flash-tts-preview']
        | Literal['lyria-3-clip-preview']
        | Literal['lyria-3-pro-preview']
    ]
):
    root: (
        str
        | Literal['gemini-2.5-computer-use-preview-10-2025']
        | Literal['gemini-2.5-flash']
        | Literal['gemini-2.5-flash-image']
        | Literal['gemini-2.5-flash-lite']
        | Literal['gemini-2.5-flash-lite-preview-09-2025']
        | Literal['gemini-2.5-flash-native-audio-preview-12-2025']
        | Literal['gemini-2.5-flash-preview-09-2025']
        | Literal['gemini-2.5-flash-preview-tts']
        | Literal['gemini-2.5-pro']
        | Literal['gemini-2.5-pro-preview-tts']
        | Literal['gemini-3-flash-preview']
        | Literal['gemini-3-pro-image-preview']
        | Literal['gemini-3-pro-preview']
        | Literal['gemini-3.1-pro-preview']
        | Literal['gemini-3.1-flash-image-preview']
        | Literal['gemini-3.1-flash-lite-preview']
        | Literal['gemini-3.1-flash-tts-preview']
        | Literal['lyria-3-clip-preview']
        | Literal['lyria-3-pro-preview']
    ) = Field(
        ...,
        description='The model that will complete your prompt.\\n\\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details.',
        title='Model',
    )


class AgentOption(
    RootModel[
        str
        | Literal['deep-research-pro-preview-12-2025']
        | Literal['deep-research-preview-04-2026']
        | Literal['deep-research-max-preview-04-2026']
    ]
):
    root: (
        str
        | Literal['deep-research-pro-preview-12-2025']
        | Literal['deep-research-preview-04-2026']
        | Literal['deep-research-max-preview-04-2026']
    ) = Field(..., description='The agent to interact with.', title='Agent')


class PlaceCitation(BaseModel):
    type: Literal['place_citation']
    place_id: str | None = Field(
        None, description='The ID of the place, in `places/{place_id}` format.'
    )
    name: str | None = Field(None, description='Title of the place.')
    url: str | None = Field(None, description='URI reference of the place.')
    review_snippets: list[ReviewSnippet] | None = Field(
        None,
        description='Snippets of reviews that are used to generate answers about the\nfeatures of a given place in Google Maps.',
    )
    start_index: int | None = Field(
        None,
        description='Start of segment of the response that is attributed to this source.\n\nIndex indicates the start of the segment, measured in bytes.',
    )
    end_index: int | None = Field(
        None, description='End of the attributed segment, exclusive.'
    )


class ImageContent(BaseModel):
    type: Literal['image']
    data: Base64Str | None = Field(None, description='The image content.')
    uri: str | None = Field(None, description='The URI of the image.')
    mime_type: MimeType | None = Field(None, description='The mime type of the image.')
    resolution: MediaResolution | None = Field(
        None, description='The resolution of the media.'
    )


class VideoContent(BaseModel):
    type: Literal['video']
    data: Base64Str | None = Field(None, description='The video content.')
    uri: str | None = Field(None, description='The URI of the video.')
    mime_type: MimeType3 | None = Field(None, description='The mime type of the video.')
    resolution: MediaResolution | None = Field(
        None, description='The resolution of the media.'
    )


class GoogleMapsResult(BaseModel):
    places: list[Places] | None = Field(None, description='The places that were found.')
    widget_context_token: str | None = Field(
        None, description='Resource name of the Google Maps widget context token.'
    )


class CodeExecutionCallStep(BaseModel):
    type: Literal['code_execution_call']
    arguments: CodeExecutionCallStepArguments = Field(
        ..., description='Required. The arguments to pass to the code execution.'
    )
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class UrlContextCallStep(BaseModel):
    type: Literal['url_context_call']
    arguments: UrlContextCallStepArguments = Field(
        ..., description='Required. The arguments to pass to the URL context.'
    )
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class GoogleSearchCallStep(BaseModel):
    type: Literal['google_search_call']
    arguments: GoogleSearchCallStepArguments = Field(
        ..., description='Required. The arguments to pass to Google Search.'
    )
    search_type: SearchType | None = Field(
        None, description='The type of search grounding enabled.'
    )
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class GoogleMapsCallStep(BaseModel):
    type: Literal['google_maps_call']
    arguments: GoogleMapsCallStepArguments | None = Field(
        None, description='The arguments to pass to the Google Maps tool.'
    )
    id: str = Field(
        ..., description='Required. A unique ID for this specific tool call.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class UrlContextResultStep(BaseModel):
    type: Literal['url_context_result']
    result: list[UrlContextResultItem] = Field(
        ..., description='Required. The results of the URL context.'
    )
    is_error: bool | None = Field(
        None, description='Whether the URL context resulted in an error.'
    )
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class GoogleSearchResultStep(BaseModel):
    type: Literal['google_search_result']
    result: list[GoogleSearchResultItem] = Field(
        ..., description='Required. The results of the Google Search.'
    )
    is_error: bool | None = Field(
        None, description='Whether the Google Search resulted in an error.'
    )
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class GoogleMapsResultItem(BaseModel):
    places: list[GoogleMapsResultPlaces] | None = None
    widget_context_token: str | None = None


class ResponseFormat(
    RootModel[
        AudioResponseFormat
        | TextResponseFormat
        | ImageResponseFormat
        | VideoResponseFormat
        | dict[str, Any]
    ]
):
    root: (
        AudioResponseFormat
        | TextResponseFormat
        | ImageResponseFormat
        | VideoResponseFormat
        | dict[str, Any]
    )


class AllowedTools(BaseModel):
    mode: ToolChoiceType | None = Field(
        None, description='The mode of the tool choice.'
    )
    tools: list[str] | None = Field(None, description='The names of the allowed tools.')


class DeepResearchAgentConfig(BaseModel):
    type: Literal['deep-research']
    thinking_summaries: ThinkingSummaries | None = Field(
        None, description='Whether to include thought summaries in the response.'
    )
    visualization: Visualization | None = Field(
        None, description='Whether to include visualizations in the response.'
    )
    collaborative_planning: bool | None = Field(
        None,
        description='Enables human-in-the-loop planning for the Deep Research agent. If set to\ntrue, the Deep Research agent will provide a research plan in its response.\nThe agent will then proceed only if the user confirms the plan in the next\nturn. .',
    )


class McpServer(BaseModel):
    type: Literal['mcp_server']
    name: str | None = Field(None, description='The name of the MCPServer.')
    url: str | None = Field(
        None,
        description='The full URL for the MCPServer endpoint.\nExample: "https://api.example.com/mcp"',
    )
    headers: dict[str, str] | None = Field(
        None,
        description='Optional: Fields for authentication headers, timeouts, etc., if needed.',
    )
    allowed_tools: list[AllowedTools] | None = Field(
        None, description='The allowed tools.'
    )


class Retrieval(BaseModel):
    type: Literal['retrieval']
    retrieval_types: list[RetrievalType] | None = Field(
        None, description='The types of file retrieval to enable.'
    )
    vertex_ai_search_config: VertexAISearchConfig | None = Field(
        None, description='Used to specify configuration for VertexAISearch.'
    )


class ModalityTokens(BaseModel):
    modality: ResponseModality | None = Field(
        None, description='The modality associated with the token count.'
    )
    tokens: int | None = Field(None, description='Number of tokens for the modality.')


class ImageDelta(BaseModel):
    type: Literal['image']
    data: Base64Str | None = None
    uri: str | None = None
    mime_type: MimeType7 | None = None
    resolution: MediaResolution | None = Field(
        None, description='The resolution of the media.'
    )


class VideoDelta(BaseModel):
    type: Literal['video']
    data: Base64Str | None = None
    uri: str | None = None
    mime_type: MimeType10 | None = None
    resolution: MediaResolution | None = Field(
        None, description='The resolution of the media.'
    )


class GoogleMapsResultDelta(BaseModel):
    type: Literal['google_maps_result']
    result: list[GoogleMapsResult] | None = Field(
        None, description='The results of the Google Maps.'
    )
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class ErrorEvent(BaseModel):
    event_type: Literal['error']
    error: Error | None = None
    event_id: str | None = Field(
        None,
        description='The event_id token to be used to resume the interaction stream, from\nthis event.',
    )


class Webhook(BaseModel):
    name: str | None = Field(
        None, description='Optional. The user-provided name of the webhook.'
    )
    uri: str = Field(
        ..., description='Required. The URI to which webhook events will be sent.'
    )
    subscribed_events: list[
        str
        | Literal['batch.succeeded']
        | Literal['batch.expired']
        | Literal['batch.failed']
        | Literal['interaction.requires_action']
        | Literal['interaction.completed']
        | Literal['interaction.failed']
        | Literal['video.generated']
    ] = Field(
        ...,
        description='Required. The events that the webhook is subscribed to.\nAvailable events:\n- batch.succeeded\n- batch.expired\n- batch.failed\n- interaction.requires_action\n- interaction.completed\n- interaction.failed\n- video.generated',
    )
    create_time: AwareDatetime | None = Field(
        None, description='Output only. The timestamp when the webhook was created.'
    )
    update_time: AwareDatetime | None = Field(
        None,
        description='Output only. The timestamp when the webhook was last updated.',
    )
    signing_secrets: list[SigningSecret] | None = Field(
        None,
        description='Output only. The signing secrets associated with this webhook.',
    )
    state: State | None = Field(
        None, description='Output only. The state of the webhook.'
    )
    new_signing_secret: str | None = Field(
        None,
        description='Output only. The new signing secret for the webhook. Only populated on create.',
    )
    id: str | None = Field(None, description='Output only. The ID of the webhook.')


class ListWebhooksResponse(BaseModel):
    webhooks: list[Webhook] | None = Field(None, description='The webhooks.')
    next_page_token: str | None = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page.\nIf this field is omitted, there are no subsequent pages.',
    )


class ResponseFormatList(RootModel[list[ResponseFormat]]):
    root: list[ResponseFormat]


class Annotation(RootModel[UrlCitation | FileCitation | PlaceCitation]):
    root: UrlCitation | FileCitation | PlaceCitation = Field(
        ...,
        description='Citation information for model-generated content.',
        discriminator='type',
    )


class GoogleMapsResultStep(BaseModel):
    type: Literal['google_maps_result']
    result: list[GoogleMapsResultItem]
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )


class ToolChoiceConfig(BaseModel):
    allowed_tools: AllowedTools | None = Field(None, description='The allowed tools.')


class Tool(
    RootModel[
        Function
        | CodeExecution
        | UrlContext
        | ComputerUse
        | McpServer
        | GoogleSearch
        | FileSearch
        | GoogleMaps
        | Retrieval
    ]
):
    root: (
        Function
        | CodeExecution
        | UrlContext
        | ComputerUse
        | McpServer
        | GoogleSearch
        | FileSearch
        | GoogleMaps
        | Retrieval
    ) = Field(
        ..., description='A tool that can be used by the model.', discriminator='type'
    )


class Usage(BaseModel):
    total_input_tokens: int | None = Field(
        None, description='Number of tokens in the prompt (context).'
    )
    input_tokens_by_modality: list[ModalityTokens] | None = Field(
        None, description='A breakdown of input token usage by modality.'
    )
    total_cached_tokens: int | None = Field(
        None,
        description='Number of tokens in the cached part of the prompt (the cached content).',
    )
    cached_tokens_by_modality: list[ModalityTokens] | None = Field(
        None, description='A breakdown of cached token usage by modality.'
    )
    total_output_tokens: int | None = Field(
        None, description='Total number of tokens across all the generated responses.'
    )
    output_tokens_by_modality: list[ModalityTokens] | None = Field(
        None, description='A breakdown of output token usage by modality.'
    )
    total_tool_use_tokens: int | None = Field(
        None, description='Number of tokens present in tool-use prompt(s).'
    )
    tool_use_tokens_by_modality: list[ModalityTokens] | None = Field(
        None, description='A breakdown of tool-use token usage by modality.'
    )
    total_thought_tokens: int | None = Field(
        None, description='Number of tokens of thoughts for thinking models.'
    )
    total_tokens: int | None = Field(
        None,
        description='Total token count for the interaction request (prompt + responses + other\ninternal tokens).',
    )
    grounding_tool_count: list[GroundingToolCount] | None = Field(
        None, description='Grounding tool count.'
    )


class TextAnnotationDelta(BaseModel):
    type: Literal['text_annotation_delta']
    annotations: list[Annotation] | None = Field(
        None, description='Citation information for model-generated content.'
    )


class TextContent(BaseModel):
    type: Literal['text']
    text: str = Field(..., description='Required. The text content.')
    annotations: list[Annotation] | None = Field(
        None, description='Citation information for model-generated content.'
    )


class ThoughtSummaryContent(RootModel[TextContent | ImageContent]):
    root: TextContent | ImageContent = Field(..., discriminator='type')


class FunctionResultSubcontent(RootModel[TextContent | ImageContent]):
    root: TextContent | ImageContent = Field(..., discriminator='type')


class ThoughtStep(BaseModel):
    type: Literal['thought']
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )
    summary: list[ThoughtSummaryContent] | None = Field(
        None, description='A summary of the thought.'
    )


class FunctionResultStep(BaseModel):
    type: Literal['function_result']
    name: str | None = Field(None, description='The name of the tool that was called.')
    is_error: bool | None = Field(
        None, description='Whether the tool call resulted in an error.'
    )
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )
    result: dict[str, Any] | list[FunctionResultSubcontent] | str = Field(
        ..., description='The result of the tool call.'
    )


class McpServerToolResultStep(BaseModel):
    type: Literal['mcp_server_tool_result']
    name: str | None = Field(
        None,
        description='Name of the tool which is called for this specific tool call.',
    )
    server_name: str | None = Field(
        None, description='The name of the used MCP server.'
    )
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )
    result: dict[str, Any] | str | list[FunctionResultSubcontent] = Field(
        ...,
        description='The output from the MCP server call. Can be simple text or rich content.',
    )


class GenerationConfig(BaseModel):
    temperature: float | None = Field(
        None, description='Controls the randomness of the output.'
    )
    top_p: float | None = Field(
        None,
        description='The maximum cumulative probability of tokens to consider when sampling.',
    )
    seed: int | None = Field(
        None, description='Seed used in decoding for reproducibility.'
    )
    stop_sequences: list[str] | None = Field(
        None,
        description='A list of character sequences that will stop output interaction.',
    )
    thinking_level: ThinkingLevel | None = Field(
        None, description='The level of thought tokens that the model should generate.'
    )
    thinking_summaries: ThinkingSummaries | None = Field(
        None, description='Whether to include thought summaries in the response.'
    )
    max_output_tokens: int | None = Field(
        None, description='The maximum number of tokens to include in the response.'
    )
    speech_config: list[SpeechConfig] | None = Field(
        None, description='Configuration for speech interaction.'
    )
    image_config: ImageConfig | None = Field(
        None, description='Configuration for image interaction.'
    )
    tool_choice: ToolChoiceType | ToolChoiceConfig | None = Field(
        None, description='The tool choice configuration.'
    )


class ThoughtSummaryDelta(BaseModel):
    type: Literal['thought_summary']
    content: ThoughtSummaryContent | None = Field(
        None, description='A new summary item to be added to the thought.'
    )


class FunctionResultDelta(BaseModel):
    type: Literal['function_result']
    name: str | None = None
    is_error: bool | None = None
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )
    result: dict[str, Any] | list[FunctionResultSubcontent] | str


class McpServerToolResultDelta(BaseModel):
    type: Literal['mcp_server_tool_result']
    name: str | None = None
    server_name: str | None = None
    call_id: str = Field(
        ..., description='Required. ID to match the ID from the function call block.'
    )
    signature: Base64Str | None = Field(
        None, description='A signature hash for backend validation.'
    )
    result: dict[str, Any] | list[FunctionResultSubcontent] | str


class StepDeltaData(
    RootModel[
        TextDelta
        | ImageDelta
        | AudioDelta
        | DocumentDelta
        | VideoDelta
        | ThoughtSummaryDelta
        | ThoughtSignatureDelta
        | TextAnnotationDelta
        | ArgumentsDelta
    ]
):
    root: (
        TextDelta
        | ImageDelta
        | AudioDelta
        | DocumentDelta
        | VideoDelta
        | ThoughtSummaryDelta
        | ThoughtSignatureDelta
        | TextAnnotationDelta
        | ArgumentsDelta
    ) = Field(..., discriminator='type')


class Content(
    RootModel[
        TextContent | ImageContent | AudioContent | DocumentContent | VideoContent
    ]
):
    root: TextContent | ImageContent | AudioContent | DocumentContent | VideoContent = (
        Field(..., description='The content of the response.', discriminator='type')
    )


class ThoughtContent(BaseModel):
    type: Literal['thought']
    signature: Base64Str | None = Field(
        None,
        description='Signature to match the backend source to be part of the generation.',
    )
    summary: list[ThoughtSummaryContent] | None = Field(
        None, description='A summary of the thought.'
    )


class Turn(BaseModel):
    role: str | None = Field(
        None,
        description='The originator of this turn. Must be user for input or model for\nmodel output.',
    )
    content: list[Content] | str | None = None


class UserInputStep(BaseModel):
    type: Literal['user_input']
    content: list[Content] | None = None


class ModelOutputStep(BaseModel):
    type: Literal['model_output']
    content: list[Content] | None = None


class ContentStart(BaseModel):
    event_type: Literal['content.start']
    index: int
    content: Content
    event_id: str | None = Field(
        None,
        description='The event_id token to be used to resume the interaction stream, from\nthis event.',
    )


class ContentDeltaData(
    RootModel[
        TextDelta
        | ImageDelta
        | AudioDelta
        | DocumentDelta
        | VideoDelta
        | ThoughtSummaryDelta
        | ThoughtSignatureDelta
        | FunctionCallDelta
        | CodeExecutionCallDelta
        | UrlContextCallDelta
        | GoogleSearchCallDelta
        | McpServerToolCallDelta
        | FileSearchCallDelta
        | GoogleMapsCallDelta
        | FunctionResultDelta
        | CodeExecutionResultDelta
        | UrlContextResultDelta
        | GoogleSearchResultDelta
        | McpServerToolResultDelta
        | FileSearchResultDelta
        | GoogleMapsResultDelta
        | TextAnnotationDelta
    ]
):
    root: (
        TextDelta
        | ImageDelta
        | AudioDelta
        | DocumentDelta
        | VideoDelta
        | ThoughtSummaryDelta
        | ThoughtSignatureDelta
        | FunctionCallDelta
        | CodeExecutionCallDelta
        | UrlContextCallDelta
        | GoogleSearchCallDelta
        | McpServerToolCallDelta
        | FileSearchCallDelta
        | GoogleMapsCallDelta
        | FunctionResultDelta
        | CodeExecutionResultDelta
        | UrlContextResultDelta
        | GoogleSearchResultDelta
        | McpServerToolResultDelta
        | FileSearchResultDelta
        | GoogleMapsResultDelta
        | TextAnnotationDelta
    ) = Field(
        ...,
        description='The delta content data for a content block.',
        discriminator='type',
    )


class StepDelta(BaseModel):
    event_type: Literal['step.delta']
    index: int
    delta: StepDeltaData
    event_id: str | None = Field(
        None,
        description='The event_id token to be used to resume the interaction stream, from\nthis event.',
    )


class Step(
    RootModel[
        UserInputStep
        | ModelOutputStep
        | ThoughtStep
        | FunctionCallStep
        | CodeExecutionCallStep
        | UrlContextCallStep
        | McpServerToolCallStep
        | GoogleSearchCallStep
        | FileSearchCallStep
        | GoogleMapsCallStep
        | FunctionResultStep
        | CodeExecutionResultStep
        | UrlContextResultStep
        | GoogleSearchResultStep
        | McpServerToolResultStep
        | FileSearchResultStep
        | GoogleMapsResultStep
    ]
):
    root: (
        UserInputStep
        | ModelOutputStep
        | ThoughtStep
        | FunctionCallStep
        | CodeExecutionCallStep
        | UrlContextCallStep
        | McpServerToolCallStep
        | GoogleSearchCallStep
        | FileSearchCallStep
        | GoogleMapsCallStep
        | FunctionResultStep
        | CodeExecutionResultStep
        | UrlContextResultStep
        | GoogleSearchResultStep
        | McpServerToolResultStep
        | FileSearchResultStep
        | GoogleMapsResultStep
    ) = Field(..., description='A step in the interaction.', discriminator='type')


class ContentDelta(BaseModel):
    event_type: Literal['content.delta']
    index: int
    delta: ContentDeltaData
    event_id: str | None = Field(
        None,
        description='The event_id token to be used to resume the interaction stream, from\nthis event.',
    )


class StepStart(BaseModel):
    event_type: Literal['step.start']
    index: int
    step: Step
    event_id: str | None = Field(
        None,
        description='The event_id token to be used to resume the interaction stream, from\nthis event.',
    )


class InteractionsInput(RootModel[str | list[Step] | list[Content] | Content]):
    root: str | list[Step] | list[Content] | Content = Field(
        ..., description='The input for the interaction.'
    )


class Interaction(BaseModel):
    model: ModelOption | None = Field(
        None, description='The name of the `Model` used for generating the interaction.'
    )
    agent: AgentOption | None = Field(
        None, description='The name of the `Agent` used for generating the interaction.'
    )
    id: str = Field(
        ...,
        description='Required. Output only. A unique identifier for the interaction completion.',
    )
    status: Status2 = Field(
        ..., description='Required. Output only. The status of the interaction.'
    )
    created: AwareDatetime = Field(
        ...,
        description='Required. Output only. The time at which the response was created in ISO 8601 format\n(YYYY-MM-DDThh:mm:ssZ).',
    )
    updated: AwareDatetime = Field(
        ...,
        description='Required. Output only. The time at which the response was last updated in ISO 8601 format\n(YYYY-MM-DDThh:mm:ssZ).',
    )
    role: str | None = Field(
        None, deprecated=True, description='Output only. The role of the interaction.'
    )
    system_instruction: str | None = Field(
        None, description='System instruction for the interaction.'
    )
    tools: list[Tool] | None = Field(
        None,
        description='A list of tool declarations the model may call during interaction.',
    )
    usage: Usage | None = Field(
        None,
        description="Output only. Statistics on the interaction request's token usage.",
    )
    response_modalities: list[ResponseModality] | None = Field(
        None,
        description='The requested modalities of the response (TEXT, IMAGE, AUDIO).',
    )
    response_mime_type: str | None = Field(
        None,
        description='The mime type of the response. This is required if response_format is set.',
    )
    previous_interaction_id: str | None = Field(
        None, description='The ID of the previous interaction, if any.'
    )
    service_tier: ServiceTier | None = Field(
        None, description='The service tier for the interaction.'
    )
    webhook_config: WebhookConfig | None = Field(
        None,
        description='Optional. Webhook configuration for receiving notifications when the\ninteraction completes.',
    )
    steps: list[Step] | None = Field(
        None, description='Output only. The steps that make up the interaction.'
    )
    input: InteractionsInput | None = None
    response_format: ResponseFormatList | ResponseFormat | None = Field(
        None,
        description='Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.',
    )
    generation_config: GenerationConfig | None = Field(
        None,
        description='Input only. Configuration parameters for the model interaction.',
    )
    agent_config: DynamicAgentConfig | DeepResearchAgentConfig | None = Field(
        None,
        description='Configuration parameters for the agent interaction.',
        discriminator='type',
    )


class CreateModelInteractionParams(BaseModel):
    model: ModelOption = Field(
        ..., description='The name of the `Model` used for generating the interaction.'
    )
    stream: bool | None = Field(
        None, description='Input only. Whether the interaction will be streamed.'
    )
    store: bool | None = Field(
        None,
        description='Input only. Whether to store the response and request for later retrieval.',
    )
    background: bool | None = Field(
        None,
        description='Input only. Whether to run the model interaction in the background.',
    )
    id: str | None = Field(
        None,
        description='Required. Output only. A unique identifier for the interaction completion.',
    )
    status: Status2 | None = Field(
        None, description='Required. Output only. The status of the interaction.'
    )
    created: AwareDatetime | None = Field(
        None,
        description='Required. Output only. The time at which the response was created in ISO 8601 format\n(YYYY-MM-DDThh:mm:ssZ).',
    )
    updated: AwareDatetime | None = Field(
        None,
        description='Required. Output only. The time at which the response was last updated in ISO 8601 format\n(YYYY-MM-DDThh:mm:ssZ).',
    )
    role: str | None = Field(
        None, deprecated=True, description='Output only. The role of the interaction.'
    )
    system_instruction: str | None = Field(
        None, description='System instruction for the interaction.'
    )
    tools: list[Tool] | None = Field(
        None,
        description='A list of tool declarations the model may call during interaction.',
    )
    usage: Usage | None = Field(
        None,
        description="Output only. Statistics on the interaction request's token usage.",
    )
    response_modalities: list[ResponseModality] | None = Field(
        None,
        description='The requested modalities of the response (TEXT, IMAGE, AUDIO).',
    )
    response_mime_type: str | None = Field(
        None,
        description='The mime type of the response. This is required if response_format is set.',
    )
    previous_interaction_id: str | None = Field(
        None, description='The ID of the previous interaction, if any.'
    )
    service_tier: ServiceTier | None = Field(
        None, description='The service tier for the interaction.'
    )
    webhook_config: WebhookConfig | None = Field(
        None,
        description='Optional. Webhook configuration for receiving notifications when the\ninteraction completes.',
    )
    steps: list[Step] | None = Field(
        None, description='Output only. The steps that make up the interaction.'
    )
    input: InteractionsInput
    response_format: ResponseFormatList | ResponseFormat | None = Field(
        None,
        description='Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.',
    )
    generation_config: GenerationConfig | None = Field(
        None,
        description='Input only. Configuration parameters for the model interaction.',
    )


class CreateAgentInteractionParams(BaseModel):
    agent: AgentOption = Field(
        ..., description='The name of the `Agent` used for generating the interaction.'
    )
    stream: bool | None = Field(
        None, description='Input only. Whether the interaction will be streamed.'
    )
    store: bool | None = Field(
        None,
        description='Input only. Whether to store the response and request for later retrieval.',
    )
    background: bool | None = Field(
        None,
        description='Input only. Whether to run the model interaction in the background.',
    )
    id: str | None = Field(
        None,
        description='Required. Output only. A unique identifier for the interaction completion.',
    )
    status: Status2 | None = Field(
        None, description='Required. Output only. The status of the interaction.'
    )
    created: AwareDatetime | None = Field(
        None,
        description='Required. Output only. The time at which the response was created in ISO 8601 format\n(YYYY-MM-DDThh:mm:ssZ).',
    )
    updated: AwareDatetime | None = Field(
        None,
        description='Required. Output only. The time at which the response was last updated in ISO 8601 format\n(YYYY-MM-DDThh:mm:ssZ).',
    )
    role: str | None = Field(
        None, deprecated=True, description='Output only. The role of the interaction.'
    )
    system_instruction: str | None = Field(
        None, description='System instruction for the interaction.'
    )
    tools: list[Tool] | None = Field(
        None,
        description='A list of tool declarations the model may call during interaction.',
    )
    usage: Usage | None = Field(
        None,
        description="Output only. Statistics on the interaction request's token usage.",
    )
    response_modalities: list[ResponseModality] | None = Field(
        None,
        description='The requested modalities of the response (TEXT, IMAGE, AUDIO).',
    )
    response_mime_type: str | None = Field(
        None,
        description='The mime type of the response. This is required if response_format is set.',
    )
    previous_interaction_id: str | None = Field(
        None, description='The ID of the previous interaction, if any.'
    )
    service_tier: ServiceTier | None = Field(
        None, description='The service tier for the interaction.'
    )
    webhook_config: WebhookConfig | None = Field(
        None,
        description='Optional. Webhook configuration for receiving notifications when the\ninteraction completes.',
    )
    steps: list[Step] | None = Field(
        None, description='Output only. The steps that make up the interaction.'
    )
    input: InteractionsInput
    response_format: ResponseFormatList | ResponseFormat | None = Field(
        None,
        description='Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.',
    )
    agent_config: DynamicAgentConfig | DeepResearchAgentConfig | None = Field(
        None,
        description='Configuration parameters for the agent interaction.',
        discriminator='type',
    )


class InteractionCreatedEvent(BaseModel):
    event_type: Literal['interaction.created']
    interaction: Interaction
    event_id: str | None = Field(
        None,
        description='The event_id token to be used to resume the interaction stream, from\nthis event.',
    )


class InteractionCompletedEvent(BaseModel):
    event_type: Literal['interaction.completed']
    interaction: Interaction = Field(
        ...,
        description='Required. The completed interaction with empty outputs to reduce the payload size.\nUse the preceding ContentDelta events for the actual output.',
    )
    event_id: str | None = Field(
        None,
        description='The event_id token to be used to resume the interaction stream, from\nthis event.',
    )


class InteractionSseEvent(
    RootModel[
        InteractionCreatedEvent
        | InteractionCompletedEvent
        | InteractionStatusUpdate
        | ErrorEvent
        | StepStart
        | StepDelta
        | StepStop
    ]
):
    root: (
        InteractionCreatedEvent
        | InteractionCompletedEvent
        | InteractionStatusUpdate
        | ErrorEvent
        | StepStart
        | StepDelta
        | StepStop
    ) = Field(..., discriminator='event_type')
# ============================================================
# LiteLLM-specific types (added manually after generation)
# ============================================================
#
# When regenerating this file, copy these types to the end.
# See README.md for regeneration instructions.

from pydantic import PrivateAttr
from typing import Union, List, Dict, Any, Optional

from litellm.types.llms.base import BaseLiteLLMOpenAIResponseObject

# Type alias for input
InteractionInput = Union[str, Content, List[Content], List[Turn]]


class InteractionsAPIResponse(BaseLiteLLMOpenAIResponseObject):
    """
    Response from the Interactions API.

    Wraps the API response with LiteLLM-specific hidden params.
    """

    id: Optional[str] = None
    object: Optional[str] = "interaction"
    model: Optional[str] = None
    agent: Optional[str] = None
    status: Optional[str] = None
    created: Optional[str] = None
    updated: Optional[str] = None
    role: Optional[str] = None
    steps: Optional[List[Dict[str, Any]]] = None
    usage: Optional[Dict[str, Any]] = None

    _hidden_params: dict = PrivateAttr(default_factory=dict)


class InteractionsAPIStreamingResponse(BaseLiteLLMOpenAIResponseObject):
    """
    Streaming response chunk from the Interactions API.

    Event types per OpenAPI spec:
    - interaction.start, interaction.status_update, interaction.complete
    - step.start, step.delta, step.stop
    - error
    """

    event_type: Optional[str] = None
    id: Optional[str] = None
    object: Optional[str] = "interaction"
    model: Optional[str] = None
    agent: Optional[str] = None
    status: Optional[str] = None
    created: Optional[str] = None
    updated: Optional[str] = None
    role: Optional[str] = None
    steps: Optional[List[Dict[str, Any]]] = None
    usage: Optional[Dict[str, Any]] = None
    delta: Optional[Dict[str, Any]] = None

    _hidden_params: dict = PrivateAttr(default_factory=dict)


class DeleteInteractionResult(BaseLiteLLMOpenAIResponseObject):
    """Result of deleting an interaction."""

    success: bool = True
    id: Optional[str] = None

    _hidden_params: dict = PrivateAttr(default_factory=dict)


class CancelInteractionResult(BaseLiteLLMOpenAIResponseObject):
    """Result of cancelling an interaction."""

    id: Optional[str] = None
    status: Optional[str] = None

    _hidden_params: dict = PrivateAttr(default_factory=dict)


# Backwards compatibility aliases
InteractionTool = Tool
InteractionToolChoiceConfig = ToolChoiceConfig
InteractionsAPIOptionalRequestParams = Dict[str, Any]
